### ISSUE TITLE
Attribute error from dataclasses

### ISSUE THREAD

**Issue by phemmylintry** [withlogicco/billit-python-sdk#11]
https://github.com/withlogicco/billit-python-sdk/blob/9127f43eed28d5c2d7da3010e9b4a72b2035d92c/billit/client.py#L118

This line throws an attribute error. I think dataclasses was references or used wrongly. According to these docs

https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict

I think dataclasses should be called as a decorator for the Invoice class 

or we don't need to call dataclasses again, should just be

```python
 self._args_api_mappings["taxes"]: asdict(taxes), 
 ```

**Comment by parisk** [comment]
Hey hey,

Now that I pay a bit more attention to it, the way this should work, according to documentation is:

```py
import dataclasses

self._args_api_mappings["taxes"]: [dataclasses.asdict(tax) for tax in taxes], 
```

Also, it looks like this should be a list of `Tax` 😄: https://github.com/withlogicco/billit-python-sdk/blob/9127f43eed28d5c2d7da3010e9b4a72b2035d92c/billit/client.py#L103

Let's open up a PR to fix these

**Comment by phemmylintry** [comment]
Got it
