### ISSUE TITLE
`Contacts` methods

### ISSUE THREAD

**Issue by parisk** [withlogicco/billit-python-sdk#28]
The `contacts` counterpard of the deprecated `customers` (https://github.com/withlogicco/billit-python-sdk/issues/13).

## Example

```py
import billit

client = billit.Client(...)

contact = client.contacts.create(
    contact_type=billit.contacts.CUSTOMER,
)
```

## Methods
- `.list()`, based off https://developer.billit.io/docs/billitdocs/b71b286083eba-list-of-contacts
- `.create()`, based off https://developer.billit.io/docs/billitdocs/fd287d44c3d0a-create-a-contact
- `.show()`, based off https://developer.billit.io/docs/billitdocs/20a6e720287bc-show-a-customer
- `.update()`, based off https://developer.billit.io/docs/billitdocs/25aea7851af37-update-a-customer
- `.delete()`, based off https://developer.billit.io/docs/billitdocs/fa358604598ff-delete-a-customer

## Constants

These constants should be available as `billit.contacts.<CONSTANT_NAME>`

- `DOMESTIC_CUSTOMER`: `1`
- `INTRA_COMMUNITY_CUSTOMER`: `2`
- `FOREIGN_CUSTOMER`: `3`
- `PRIVATE_INDIVIDUAL`: `4`
- `CUSTOMER`: `1`
- `SUPPLIER`: `2`
- `CUSTOMER_AND_SUPPLIER`: `3`

**Comment by phemmylintry** [comment]
@parisk Do I create a separate module for contacts now? Also, since customer is depcreiated, should I replace the customer client or just create a new contact client

**Comment by parisk** [comment]
We will leave `.customers` there, until it gets completely removed from the API. Let's keep the `Contacts` SubClient in `clients.py` and we will refactor it later, so we can move each subclient to its own file.
